"""Run DM-TM ablation: isolating Stage 1 (direction) vs Stage 2 (magnitude).

Tests three configurations under sign_flip and ipm attacks at f=0.3 on the
Barcelona LTE dataset (all 5 seeds):
  - dm_mag_only (direction_trim_ratio=0.0, trim_ratio=0.1)
  - dm_dir_only (direction_trim_ratio=0.2, trim_ratio=0.0)
  - dm_full     (direction_trim_ratio=0.2, trim_ratio=0.1)

Writes results_real/table_dmtm_ablation.tex and results_real/dm_ablation.csv.
"""
from __future__ import annotations

import csv
import math
import sys
import time
from pathlib import Path
from statistics import mean, stdev

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from oran_fed_robust.aggregation import build_aggregator
from oran_fed_robust.data.real_traffic import load_real_federated_dataset
from oran_fed_robust.training import FederatedTrainer

SEEDS = [0, 1, 2, 3, 4]
ROUNDS = 200
ATTACKS = ["sign_flip", "ipm", "none"]
ATTACK_SCALE = {"ipm": 0.5, "sign_flip": 5.0, "none": 0.5}

CONFIGS = {
    "dm_mag_only": {"trim_ratio": 0.1, "direction_trim_ratio": 0.0},
    "dm_dir_only": {"trim_ratio": 0.0, "direction_trim_ratio": 0.2},
    "dm_full":     {"trim_ratio": 0.1, "direction_trim_ratio": 0.2},
}
LABELS = {
    "dm_mag_only": "Magnitude filter only (Stage 2)",
    "dm_dir_only": "Direction filter only (Stage 1)",
    "dm_full":     "\\textbf{DM-TM full (Stage 1 + Stage 2)}",
}


def ci95(xs):
    return 1.96 * stdev(xs) / math.sqrt(len(xs)) if len(xs) > 1 else 0.0


def run_single(cfg_kwargs, attack, f, seed):
    clients, test, root = load_real_federated_dataset(n_clients=50, seed=seed)
    nf = clients[0].x.shape[1]
    agg = build_aggregator("dm_trimmed_mean", **cfg_kwargs)
    comp = 0.0 if attack == "none" else f
    tr = FederatedTrainer(
        clients, test, root, agg, n_features=nf, n_classes=5,
        attack_name=attack, compromise_fraction=comp,
        attack_scale=ATTACK_SCALE.get(attack, 5.0),
        participants_per_round=20, local_epochs=2, lr=0.05, batch_size=64,
        seed=seed,
    )
    final = tr.fit(ROUNDS)[-1]
    return final.accuracy, final.macro_f1


def main():
    out = Path(__file__).resolve().parents[1] / "results_real"
    out.mkdir(parents=True, exist_ok=True)
    rows = []
    summary = {}
    t0 = time.time()

    # First run clean reference per config
    clean_map = {}
    for cname, ckwargs in CONFIGS.items():
        accs = []
        for s in SEEDS:
            acc, f1 = run_single(ckwargs, "none", 0.0, s)
            accs.append(acc)
            rows.append(dict(config=cname, attack="none", f=0.0, seed=s, accuracy=acc, macro_f1=f1))
        clean_map[cname] = mean(accs)
        summary[(cname, "none")] = (mean(accs), ci95(accs))
        print(f"clean {cname}: {mean(accs)*100:.2f}%")

    for attack in ["sign_flip", "ipm"]:
        for cname, ckwargs in CONFIGS.items():
            accs, f1s = [], []
            for s in SEEDS:
                acc, f1 = run_single(ckwargs, attack, 0.3, s)
                accs.append(acc)
                f1s.append(f1)
                rows.append(dict(config=cname, attack=attack, f=0.3, seed=s, accuracy=acc, macro_f1=f1))
            summary[(cname, attack)] = (mean(accs), ci95(accs))
            print(f"  {attack} {cname}: {mean(accs)*100:.2f}% (+/- {ci95(accs)*100:.2f}%)")

    with (out / "dm_ablation.csv").open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["config", "attack", "f", "seed", "accuracy", "macro_f1"])
        w.writeheader()
        w.writerows(rows)

    # Emit LaTeX table
    lines = [
        "% Auto-generated by run_dm_ablation.py -- measured on Barcelona LTE dataset (f=0.3, 5 seeds).",
        "\\begin{tabular}{lccc}", "\\toprule",
        "\\textbf{Variant} & \\textbf{Clean (no attack)} & \\textbf{Sign-flip ($f=0.3$)} & \\textbf{IPM ($f=0.3$)} \\\\",
        "\\midrule",
    ]
    for cname in ["dm_mag_only", "dm_dir_only", "dm_full"]:
        cacc, cci = summary[(cname, "none")]
        sacc, sci = summary[(cname, "sign_flip")]
        iacc, ici = summary[(cname, "ipm")]
        row = (f"{LABELS[cname]} & {cacc*100:.1f}$\\pm${cci*100:.1f} & "
               f"{sacc*100:.1f}$\\pm${sci*100:.1f} & {iacc*100:.1f}$\\pm${ici*100:.1f} \\\\")
        lines.append(row)
    lines += ["\\bottomrule", "\\end{tabular}"]
    table_path = out / "table_dmtm_ablation.tex"
    table_path.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", table_path, f"in {time.time()-t0:.1f}s")


if __name__ == "__main__":
    main()
